# Generated by Django 5.0.6 on 2024-09-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0004_kaspishop_active_in_kaspishop_example_kaspishop_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaspishop',
            name='active_in',
        ),
        migrations.RemoveField(
            model_name='kaspishop',
            name='example',
        ),
        migrations.RemoveField(
            model_name='kaspishop',
            name='tags',
        ),
    ]
